/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import control.Control;
import dao.CuidadorDAO;
import dao.EmpleadoDAO;
import dao.EspecieDAO;
import exceptions.DAOException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import objetos.Cuidador;
import objetos.Empleado;
import objetos.Especie;
import org.bson.types.ObjectId;
import tables.CuidadorList;

/**
 *
 * @author maikr
 */
public class CuidadorDialog extends javax.swing.JDialog {

    private final EspecieDAO especieDAO;
    private final CuidadorDAO cuidadorDAO;
    private final EmpleadoDAO empleadoDAO;
    private CuidadorList modelo;
    private Cuidador cuidador;

    /**
     * Creates new form CuidadorDialogo
     *
     * @param parent
     * @param modal
     * @param id
     * @param experto
     * @param basico
     * @param fecha
     * @param especieCuidada
     * @param nombre
     */
    public CuidadorDialog(java.awt.Frame parent, boolean modal, ObjectId id, String experto, String basico, LocalDateTime fecha, String especieCuidada, String nombre) {
        super(parent, modal);
        initComponents();
        modelo = new CuidadorList();
        especieDAO = new EspecieDAO();
        cuidadorDAO = new CuidadorDAO();
        empleadoDAO = new EmpleadoDAO();
        cuidador = new Cuidador(id, experto, basico, fecha, especieCuidada, nombre);
        comboExperto();
        comboBasico();
        comboCuidado();
        comboEmpleado();
        
    }

    /**
     * Creates new form CuidadorDialogo
     *
     * @param parent
     * @param modal
     */
    public CuidadorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo = new CuidadorList();
        especieDAO = new EspecieDAO();
        cuidadorDAO = new CuidadorDAO();
        empleadoDAO = new EmpleadoDAO();
        comboExperto();
        comboBasico();
        comboCuidado();
        comboEmpleado();
    }

    public void asignarDatos() {
        especieBasicoCombobox.setSelectedIndex(especieDAO.list().indexOf(cuidador.getBasico()));
    }
    
    private void comboExperto() {
        especieExpertoCombobox.removeAllItems();
        ArrayList<Especie> listaEspecie = (ArrayList<Especie>) this.especieDAO.list();
        for (Especie especie1 : listaEspecie) {
            this.especieExpertoCombobox.addItem(especie1.getNombreCientifico());
        }
    }

    private void comboBasico() {
        especieBasicoCombobox.removeAllItems();
        ArrayList<Especie> listaEspecie = (ArrayList<Especie>) this.especieDAO.list();
        for (Especie especie1 : listaEspecie) {
            this.especieBasicoCombobox.addItem(especie1.getNombreCientifico());
        }
    }

    private void comboCuidado() {
        empleadoCombobox.removeAllItems();
        ArrayList<Especie> listaEspecie = (ArrayList<Especie>) this.especieDAO.list();
        for (Especie especie1 : listaEspecie) {
            this.empleadoCombobox.addItem(especie1.getNombreCientifico());
        }
    }

    private void comboEmpleado() {
        especieCuidadaCombobox.removeAllItems();
        ArrayList<Empleado> listaEspecie = (ArrayList<Empleado>) this.empleadoDAO.list();
        for (Empleado emp : listaEspecie) {
            this.especieCuidadaCombobox.addItem(emp.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaCuidadoDatetimePicker = new com.github.lgooddatepicker.components.DateTimePicker();
        empleadoCombobox = new javax.swing.JComboBox<>();
        especieCuidadaCombobox = new javax.swing.JComboBox<>();
        cuidadorRegistrarBoton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        especieExpertoCombobox = new javax.swing.JComboBox<>();
        especieBasicoCombobox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Empleado");

        jLabel4.setText("Especie cuidada");

        jLabel3.setText("Fecha de cuidado");

        cuidadorRegistrarBoton.setText("Registrar");
        cuidadorRegistrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuidadorRegistrarBotonActionPerformed(evt);
            }
        });

        jLabel19.setText("Especie básico");

        jLabel18.setText("Especie experto");

        especieExpertoCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        especieBasicoCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(especieCuidadaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(empleadoCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(especieExpertoCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuidadorRegistrarBoton)
                                    .addComponent(especieBasicoCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaCuidadoDatetimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especieCuidadaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(especieExpertoCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(especieBasicoCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuidadorRegistrarBoton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fechaCuidadoDatetimePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cuidadorRegistrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuidadorRegistrarBotonActionPerformed
        String especieCuidada = (String) especieCuidadaCombobox.getSelectedItem();
        String empleado = (String) empleadoCombobox.getSelectedItem();
        LocalDateTime fecha = fechaCuidadoDatetimePicker.getDateTimeStrict();
        String especieExperto = (String) especieExpertoCombobox.getSelectedItem();
        String especieBasico = (String) especieBasicoCombobox.getSelectedItem();

        try {
            Control.createCuidador(especieCuidada, empleado, fecha, especieExperto, especieBasico);
            JOptionPane.showMessageDialog(null, "Cuidador Creado");
        } catch (DAOException e) {
            JOptionPane.showMessageDialog(null, "Cuidador no creado.");
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cuidadorRegistrarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuidadorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuidadorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuidadorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuidadorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CuidadorDialog dialog = new CuidadorDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cuidadorRegistrarBoton;
    private javax.swing.JComboBox<String> empleadoCombobox;
    private javax.swing.JComboBox<String> especieBasicoCombobox;
    private javax.swing.JComboBox<String> especieCuidadaCombobox;
    private javax.swing.JComboBox<String> especieExpertoCombobox;
    private com.github.lgooddatepicker.components.DateTimePicker fechaCuidadoDatetimePicker;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
