/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import control.Control;
import dao.*;
import exceptions.DAOException;
import java.awt.HeadlessException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import objetos.*;
import org.bson.types.ObjectId;
import tables.*;

/**
 *
 * @author maikr
 */
public final class MainJFrame extends javax.swing.JFrame {

    private final HabitatDAO habitatDAO;
    private final EspecieDAO especieDAO;
    private final ZonaDAO zonaDAO;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.habitatDAO = new HabitatDAO();
        this.especieDAO = new EspecieDAO();
        this.zonaDAO = new ZonaDAO();
        comboHabitat();
        cargarTablaEspecie();
        comboEspecie();
        habitatActualizarTabla();
        cargarTablaEmpleado();
        cargarTablaZona();
        cargarTablaCuidador();
    }

    public void comboHabitat() {

        ArrayList<Habitat> listaHabitat = (ArrayList<Habitat>) this.habitatDAO.list();
        for (Habitat habitat : listaHabitat) {

            this.EspecieHabitatComboBox.addItem(habitat.getNombre());

        }
    }

    public void comboEspecie() {
        zonaEspeciesComboBox.removeAllItems();
        ArrayList<Especie> listaEspecie = (ArrayList<Especie>) this.especieDAO.list();
        for (Especie especie1 : listaEspecie) {
            this.zonaEspeciesComboBox.addItem(especie1.getNombreCientifico());
        }
    }

    public void cargarTablaEspecie() {
        try {
            List<Especie> especies = Control.searchEspecie();
            EspeciesTable table = new EspeciesTable(especies);
            especiesTable.setModel(table);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }

    public void cargarTablaEmpleado() {
        try {
            List<Empleado> empleados = Control.searchEmpleado("");
            EmpleadoTable table = new EmpleadoTable(empleados);
            empleadoTable.setModel(table);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void cargarTablaZona() {
        try {
            List<Zona> zonas = Control.searchZona("");
            ZonaTable table = new ZonaTable(zonas);
            zonaTable.setModel(table);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void cargarTablaCuidador() {
        try {
            cuidadoresTable.setModel(new CuidadorTable(Control.listCuidador()));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        especieDescripcionTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        EspecieHabitatComboBox = new javax.swing.JComboBox<>();
        especieNombreTextField = new javax.swing.JTextField();
        especieNombreCientificoTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        especiesTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        especieRegistrarBoton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        especieActualizarBoton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        habitatNombreTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        habitatScrollPane = new javax.swing.JScrollPane();
        habitatTable = new javax.swing.JTable();
        habitatRegistrarBoton = new javax.swing.JButton();
        habtitatEditarBoton = new javax.swing.JButton();
        habitatEliminarBoton = new javax.swing.JButton();
        habitatLimpiarBoton = new javax.swing.JButton();
        habitatClimaCombobox = new javax.swing.JComboBox<>();
        habitatVegetacionCombobox = new javax.swing.JComboBox<>();
        habitatContinenteCombobox = new javax.swing.JComboBox<>();
        habitatBuscarBoton = new javax.swing.JButton();
        habitatIdTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        empleadoNombreTextField = new javax.swing.JTextField();
        empleadoTelefonoTextField = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        empleadoTable = new javax.swing.JTable();
        jTextField11 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        empleadoRegistrarBoton = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        empleadoFechaIniciodatePicker = new com.github.lgooddatepicker.components.DatePicker();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        zonaEspeciesComboBox = new javax.swing.JComboBox<>();
        zonaExtencionTextField = new javax.swing.JTextField();
        zonaNombreTextField = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        zonaTable = new javax.swing.JTable();
        zonaRegistrarBoton = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        zonaBuscarTextField = new javax.swing.JTextField();
        zonaBuscarBoton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        recorridosTable = new javax.swing.JTable();
        cuidadoresScrollPane = new javax.swing.JScrollPane();
        cuidadoresTable = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        itinerarioRegistrarCuidadorBoton = new javax.swing.JButton();
        itinerarioRegistrarRecorridoBoton = new javax.swing.JButton();
        itinerarioCuidadorEditarBoton = new javax.swing.JButton();
        cuidadorActualizarBoton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        quejasTables = new javax.swing.JTable();
        quejasRegistrarBoton = new javax.swing.JButton();
        quejasEliminarBoton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        quejaDescripcionTextFileld = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        quejaEmailTextFile = new javax.swing.JTextField();
        quejaTelefonoTextField = new javax.swing.JTextField();
        quejaActualizarBoton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Nombre Científico");

        jLabel3.setText("Descripción de la especie");

        especieDescripcionTextArea.setColumns(20);
        especieDescripcionTextArea.setRows(5);
        jScrollPane1.setViewportView(especieDescripcionTextArea);

        jLabel4.setText("Hábitad");

        EspecieHabitatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecieHabitatComboBoxActionPerformed(evt);
            }
        });

        especiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Nombre Científico", "Descripción", "Hábitad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(especiesTable);
        if (especiesTable.getColumnModel().getColumnCount() > 0) {
            especiesTable.getColumnModel().getColumn(0).setResizable(false);
            especiesTable.getColumnModel().getColumn(1).setResizable(false);
            especiesTable.getColumnModel().getColumn(2).setResizable(false);
            especiesTable.getColumnModel().getColumn(3).setResizable(false);
            especiesTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel5.setText("Especies Registradas");

        especieRegistrarBoton.setText("Registrar");
        especieRegistrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especieRegistrarBotonActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");

        jButton3.setText("Editar");

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        especieActualizarBoton.setText("Actualizar");
        especieActualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especieActualizarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(especieRegistrarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton4))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(especieNombreCientificoTextField)
                                            .addComponent(especieNombreTextField)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(EspecieHabitatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(especieActualizarBoton)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(especieNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(especieNombreCientificoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EspecieHabitatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especieRegistrarBoton)
                    .addComponent(jButton2))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(especieActualizarBoton)
                .addGap(58, 58, 58))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Especie", jPanel2);

        jLabel6.setText("Nombre");

        jLabel7.setText("Clima");

        jLabel8.setText("Tipo de vegetacion");

        jLabel9.setText("Continente");

        habitatScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                habitatScrollPaneMouseClicked(evt);
            }
        });

        habitatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Clima", "Tipo de vegetacion", "Continente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        habitatTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                habitatTableMouseClicked(evt);
            }
        });
        habitatScrollPane.setViewportView(habitatTable);
        if (habitatTable.getColumnModel().getColumnCount() > 0) {
            habitatTable.getColumnModel().getColumn(0).setResizable(false);
            habitatTable.getColumnModel().getColumn(1).setResizable(false);
            habitatTable.getColumnModel().getColumn(2).setResizable(false);
            habitatTable.getColumnModel().getColumn(4).setResizable(false);
        }

        habitatRegistrarBoton.setText("Registrar");
        habitatRegistrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitatRegistrarBotonActionPerformed(evt);
            }
        });

        habtitatEditarBoton.setText("Editar");
        habtitatEditarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habtitatEditarBotonActionPerformed(evt);
            }
        });

        habitatEliminarBoton.setText("Eliminar");
        habitatEliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitatEliminarBotonActionPerformed(evt);
            }
        });

        habitatLimpiarBoton.setText("Limpiar");
        habitatLimpiarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitatLimpiarBotonActionPerformed(evt);
            }
        });

        habitatClimaCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cálido", "Templado", "Frío" }));
        habitatClimaCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitatClimaComboboxActionPerformed(evt);
            }
        });

        habitatVegetacionCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desierto", "Tundra", "Taiga", "Bosque", "Selva", "Savana" }));

        habitatContinenteCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asia", "America", "Africa", "Antartida", "Europa", "Oceania" }));

        habitatBuscarBoton.setText("Buscar");
        habitatBuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitatBuscarBotonActionPerformed(evt);
            }
        });

        habitatIdTextField.setEditable(false);
        habitatIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitatIdTextFieldActionPerformed(evt);
            }
        });

        jLabel20.setText("ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(habitatRegistrarBoton)
                .addGap(81, 81, 81)
                .addComponent(habtitatEditarBoton)
                .addGap(59, 59, 59)
                .addComponent(habitatEliminarBoton)
                .addGap(69, 69, 69)
                .addComponent(habitatBuscarBoton)
                .addGap(54, 54, 54)
                .addComponent(habitatLimpiarBoton)
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habitatScrollPane))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(habitatIdTextField)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(habitatNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(habitatClimaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(habitatVegetacionCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(habitatContinenteCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(habitatNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(habitatClimaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(habitatVegetacionCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(habitatContinenteCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(habitatIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)))
                .addGap(21, 21, 21)
                .addComponent(habitatScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habitatRegistrarBoton)
                    .addComponent(habtitatEditarBoton)
                    .addComponent(habitatEliminarBoton)
                    .addComponent(habitatLimpiarBoton)
                    .addComponent(habitatBuscarBoton))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hábitat", jPanel3);

        jLabel14.setText("Nombre");

        jLabel15.setText("Teléfono");

        jLabel16.setText("Fecha de inicio");

        empleadoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Teléfono", "Fecha de inicio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(empleadoTable);
        if (empleadoTable.getColumnModel().getColumnCount() > 0) {
            empleadoTable.getColumnModel().getColumn(0).setResizable(false);
            empleadoTable.getColumnModel().getColumn(1).setResizable(false);
            empleadoTable.getColumnModel().getColumn(2).setResizable(false);
            empleadoTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton14.setText("Buscar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        empleadoRegistrarBoton.setText("Registrar");
        empleadoRegistrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoRegistrarBotonActionPerformed(evt);
            }
        });

        jButton16.setText("Editar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Eliminar");

        jButton18.setText("Actualizar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(empleadoRegistrarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton17))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empleadoNombreTextField)
                            .addComponent(empleadoTelefonoTextField)
                            .addComponent(empleadoFechaIniciodatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(empleadoNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(empleadoTelefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoFechaIniciodatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empleadoRegistrarBoton)
                    .addComponent(jButton18)
                    .addComponent(jButton16)
                    .addComponent(jButton17))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Empleado", jPanel5);

        jLabel10.setText("Nombre");

        jLabel11.setText("Extención");

        jLabel12.setText("especies");

        zonaNombreTextField.setToolTipText("");

        zonaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Extención", "especies"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(zonaTable);
        if (zonaTable.getColumnModel().getColumnCount() > 0) {
            zonaTable.getColumnModel().getColumn(0).setResizable(false);
            zonaTable.getColumnModel().getColumn(1).setResizable(false);
            zonaTable.getColumnModel().getColumn(2).setResizable(false);
            zonaTable.getColumnModel().getColumn(3).setResizable(false);
        }

        zonaRegistrarBoton.setText("Registrar");
        zonaRegistrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonaRegistrarBotonActionPerformed(evt);
            }
        });

        jButton10.setText("Editar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Eliminar");

        jButton12.setText("Limpiar");

        jLabel13.setText("Buscar");

        zonaBuscarBoton.setText("Busca");
        zonaBuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zonaBuscarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zonaExtencionTextField))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(zonaEspeciesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zonaNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zonaRegistrarBoton)
                            .addComponent(jButton11))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton12)
                            .addComponent(jButton10))))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zonaBuscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zonaBuscarBoton)
                        .addContainerGap(348, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(zonaNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(zonaExtencionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(zonaEspeciesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zonaRegistrarBoton)
                    .addComponent(jButton10))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(zonaBuscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zonaBuscarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Zona", jPanel4);

        recorridosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Guía", "Num. Personas", "Num. Especies", "Zonas", "Distancia", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(recorridosTable);
        if (recorridosTable.getColumnModel().getColumnCount() > 0) {
            recorridosTable.getColumnModel().getColumn(0).setResizable(false);
            recorridosTable.getColumnModel().getColumn(1).setResizable(false);
            recorridosTable.getColumnModel().getColumn(2).setResizable(false);
            recorridosTable.getColumnModel().getColumn(3).setResizable(false);
            recorridosTable.getColumnModel().getColumn(4).setResizable(false);
            recorridosTable.getColumnModel().getColumn(5).setResizable(false);
            recorridosTable.getColumnModel().getColumn(6).setResizable(false);
        }

        cuidadoresScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuidadoresScrollPaneMouseClicked(evt);
            }
        });

        cuidadoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Especie Experto", "Especie Basico", "Especie Ciudado", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cuidadoresScrollPane.setViewportView(cuidadoresTable);
        if (cuidadoresTable.getColumnModel().getColumnCount() > 0) {
            cuidadoresTable.getColumnModel().getColumn(0).setResizable(false);
            cuidadoresTable.getColumnModel().getColumn(1).setResizable(false);
            cuidadoresTable.getColumnModel().getColumn(2).setResizable(false);
            cuidadoresTable.getColumnModel().getColumn(3).setResizable(false);
            cuidadoresTable.getColumnModel().getColumn(4).setResizable(false);
            cuidadoresTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel25.setText("Cuidadores");

        jLabel26.setText("Recorridos");

        itinerarioRegistrarCuidadorBoton.setText("Registrar");
        itinerarioRegistrarCuidadorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itinerarioRegistrarCuidadorBotonActionPerformed(evt);
            }
        });

        itinerarioRegistrarRecorridoBoton.setText("Registrar");
        itinerarioRegistrarRecorridoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itinerarioRegistrarRecorridoBotonActionPerformed(evt);
            }
        });

        itinerarioCuidadorEditarBoton.setText("Editar");
        itinerarioCuidadorEditarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itinerarioCuidadorEditarBotonActionPerformed(evt);
            }
        });

        cuidadorActualizarBoton.setText("Actualizar");
        cuidadorActualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuidadorActualizarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuidadoresScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(itinerarioRegistrarCuidadorBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itinerarioCuidadorEditarBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cuidadorActualizarBoton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(itinerarioRegistrarRecorridoBoton)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(cuidadoresScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itinerarioRegistrarCuidadorBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itinerarioRegistrarRecorridoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itinerarioCuidadorEditarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuidadorActualizarBoton))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Itinerario", jPanel7);

        quejasTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Num. Personas", "Num. Especies", "Zonas", "Distacia", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(quejasTables);

        quejasRegistrarBoton.setText("Registrar");

        quejasEliminarBoton.setText("Eliminar");

        jLabel17.setText("Queja:");

        quejaDescripcionTextFileld.setColumns(20);
        quejaDescripcionTextFileld.setRows(5);
        jScrollPane8.setViewportView(quejaDescripcionTextFileld);

        jLabel18.setText("Email:");

        jLabel19.setText("Telefono:");

        quejaActualizarBoton.setText("Actualizar");
        quejaActualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quejaActualizarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(quejasRegistrarBoton)
                        .addGap(214, 214, 214)
                        .addComponent(quejasEliminarBoton))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quejaEmailTextFile, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quejaTelefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(quejaActualizarBoton)
                .addGap(60, 60, 60))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quejaActualizarBoton)
                .addGap(1, 1, 1)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(quejaEmailTextFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quejaTelefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(86, 86, 86))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quejasRegistrarBoton)
                    .addComponent(quejasEliminarBoton))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quejas", jPanel8);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void empleadoRegistrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoRegistrarBotonActionPerformed
        String nombre, telefono;
        nombre = empleadoNombreTextField.getText();
        telefono = empleadoTelefonoTextField.getText();
        LocalDate fechaInicio = this.empleadoFechaIniciodatePicker.getDate();
        try {
            Control.createEmpleado(nombre, telefono, fechaInicio.atStartOfDay());
            JOptionPane.showMessageDialog(null, "Empleado Creado");
        } catch (DAOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_empleadoRegistrarBotonActionPerformed

    private void zonaBuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zonaBuscarBotonActionPerformed
        try {
            String nombre = zonaBuscarTextField.getText();
            List<Zona> zonas = Control.searchZona(nombre);
            ZonaTable table = new ZonaTable(zonas);
            zonaTable.setModel(table);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_zonaBuscarBotonActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void zonaRegistrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zonaRegistrarBotonActionPerformed

        String nombre = zonaNombreTextField.getText();
        int extencion = Integer.parseInt(zonaExtencionTextField.getText());
        String especies = zonaEspeciesComboBox.getItemAt(zonaEspeciesComboBox.getSelectedIndex());
        try {
            Control.createZona(nombre, extencion, especies);
            JOptionPane.showMessageDialog(null, "Empleado Creado");
        } catch (DAOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_zonaRegistrarBotonActionPerformed

    private void habitatRegistrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitatRegistrarBotonActionPerformed
        String clima, vegetacion, continente, nombre;
        nombre = habitatNombreTextField.getText();
        vegetacion = habitatVegetacionCombobox.getItemAt(habitatVegetacionCombobox.getSelectedIndex());
        clima = habitatClimaCombobox.getItemAt(habitatClimaCombobox.getSelectedIndex());
        continente = habitatContinenteCombobox.getItemAt(habitatContinenteCombobox.getSelectedIndex());
        try {
            Control.createHabitat(clima, vegetacion, continente, nombre);
            JOptionPane.showMessageDialog(null, "Habitat Creado");
        } catch (DAOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_habitatRegistrarBotonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void habitatBuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitatBuscarBotonActionPerformed
        try {
            String nombre = habitatNombreTextField.getText();
            List<Habitat> habitats = Control.searchHabitat(nombre);
            HabitatTable table = new HabitatTable(habitats);
            habitatTable.setModel(table);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_habitatBuscarBotonActionPerformed

    private void itinerarioRegistrarRecorridoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itinerarioRegistrarRecorridoBotonActionPerformed
        JRecorrido ventana = new JRecorrido();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_itinerarioRegistrarRecorridoBotonActionPerformed

    private void quejaActualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quejaActualizarBotonActionPerformed
        try {

            List<Itinerario> itinerarios = Control.listItinerario();
            ItinerarioTable table = new ItinerarioTable(itinerarios);
            quejasTables.setModel(table);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_quejaActualizarBotonActionPerformed

    private void EspecieHabitatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecieHabitatComboBoxActionPerformed
        Habitat habitat = new Habitat();

    }//GEN-LAST:event_EspecieHabitatComboBoxActionPerformed

    private void habitatClimaComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitatClimaComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habitatClimaComboboxActionPerformed

    private void especieRegistrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieRegistrarBotonActionPerformed
        String nombre, nom_cientifico, descripcion, habitat;
        nombre = especieNombreTextField.getText();
        nom_cientifico = especieNombreCientificoTextField.getText();
        descripcion = especieDescripcionTextArea.getText();
        habitat = EspecieHabitatComboBox.getItemAt(EspecieHabitatComboBox.getSelectedIndex());
        try {
            Control.createEspecie(nombre, nom_cientifico, descripcion, habitat);
            JOptionPane.showMessageDialog(null, "Especie Creada");
            comboEspecie();
        } catch (DAOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_especieRegistrarBotonActionPerformed

    private void especieActualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieActualizarBotonActionPerformed
        cargarTablaEspecie();
    }//GEN-LAST:event_especieActualizarBotonActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
            String nombre = empleadoNombreTextField.getText();
            List<Empleado> empleados = Control.searchEmpleado(nombre);
            EmpleadoTable table = new EmpleadoTable(empleados);
            empleadoTable.setModel(table);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void habitatIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitatIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habitatIdTextFieldActionPerformed

    private void habitatScrollPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habitatScrollPaneMouseClicked

    }//GEN-LAST:event_habitatScrollPaneMouseClicked

    private void habitatTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habitatTableMouseClicked
        int row = habitatTable.getSelectedRow();
        int column = 0;

        String[] climas = new String[]{"Cálido", "Templado", "Frío"};
        String[] vegetaciones = new String[]{"Desierto", "Tundra", "Taiga", "Bosque", "Selva", "Savana"};
        String[] continentes = new String[]{"Asia", "America", "Africa", "Antartida", "Europa", "Oceania"};

        String id = habitatTable.getModel().getValueAt(row, column).toString();
        String nombre = habitatTable.getModel().getValueAt(row, ++column).toString();
        String clima = habitatTable.getModel().getValueAt(row, ++column).toString();
        String vegetacion = habitatTable.getModel().getValueAt(row, ++column).toString();
        String continente = habitatTable.getModel().getValueAt(row, ++column).toString();

        habitatIdTextField.setText(id);
        habitatNombreTextField.setText(nombre);

        for (int i = 0; i < climas.length; i++) {
            if (clima.equals(climas[i])) {
                habitatClimaCombobox.setSelectedIndex(i);
            }
        }

        for (int i = 0; i < vegetaciones.length; i++) {
            if (vegetacion.equals(vegetaciones[i])) {
                habitatVegetacionCombobox.setSelectedIndex(i);
            }
        }

        for (int i = 0; i < continentes.length; i++) {
            if (continente.equals(continentes[i])) {
                habitatContinenteCombobox.setSelectedIndex(i);
            }
        }

    }//GEN-LAST:event_habitatTableMouseClicked

    private void habtitatEditarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habtitatEditarBotonActionPerformed
        String clima, vegetacion, continente, nombre;
        ObjectId id = new ObjectId(habitatIdTextField.getText());
        nombre = habitatNombreTextField.getText();
        vegetacion = habitatVegetacionCombobox.getItemAt(habitatVegetacionCombobox.getSelectedIndex());
        clima = habitatClimaCombobox.getItemAt(habitatClimaCombobox.getSelectedIndex());
        continente = habitatContinenteCombobox.getItemAt(habitatContinenteCombobox.getSelectedIndex());
        try {
            Control.updateHabitat(id, clima, vegetacion, continente, nombre);
            JOptionPane.showMessageDialog(null, "El habitat se editó correctamente.");
        } catch (DAOException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "El habitat no se pudo editar, verifica la información",
                    "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        habitatActualizarTabla();
    }//GEN-LAST:event_habtitatEditarBotonActionPerformed

    private void habitatEliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitatEliminarBotonActionPerformed
        String clima, vegetacion, continente, nombre;
        ObjectId id = new ObjectId(habitatIdTextField.getText());
        nombre = habitatNombreTextField.getText();
        vegetacion = habitatVegetacionCombobox.getItemAt(habitatVegetacionCombobox.getSelectedIndex());
        clima = habitatClimaCombobox.getItemAt(habitatClimaCombobox.getSelectedIndex());
        continente = habitatContinenteCombobox.getItemAt(habitatContinenteCombobox.getSelectedIndex());
        try {
            Control.deleteHabitat(id, clima, vegetacion, continente, nombre);
            JOptionPane.showMessageDialog(null, "El habitat se borró correctamente.");
        } catch (DAOException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "El habitat no se pudo borrar, verifica la información",
                    "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        habitatActualizarTabla();
    }//GEN-LAST:event_habitatEliminarBotonActionPerformed

    private void habitatLimpiarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitatLimpiarBotonActionPerformed
        habitatIdTextField.setText("");
        habitatNombreTextField.setText("");
        habitatVegetacionCombobox.setSelectedIndex(0);
        habitatClimaCombobox.setSelectedIndex(0);
        habitatContinenteCombobox.setSelectedIndex(0);
    }//GEN-LAST:event_habitatLimpiarBotonActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void itinerarioRegistrarCuidadorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itinerarioRegistrarCuidadorBotonActionPerformed
        CuidadorDialog d = new CuidadorDialog(this, true);
        d.setVisible(true);
    }//GEN-LAST:event_itinerarioRegistrarCuidadorBotonActionPerformed

    private void cuidadoresScrollPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuidadoresScrollPaneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cuidadoresScrollPaneMouseClicked

    private void itinerarioCuidadorEditarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itinerarioCuidadorEditarBotonActionPerformed
        String nombre, experto, basico, especieCuidada;
        ObjectId id;
        LocalDateTime fecha;

        int row = cuidadoresTable.getSelectedRow();
        int column = 0;

        id = new ObjectId(cuidadoresTable.getModel().getValueAt(row, column).toString());

        nombre = cuidadoresTable.getModel().getValueAt(row, ++column).toString();
        experto = cuidadoresTable.getModel().getValueAt(row, ++column).toString();
        basico = cuidadoresTable.getModel().getValueAt(row, ++column).toString();
        especieCuidada = cuidadoresTable.getModel().getValueAt(row, ++column).toString();
        fecha = LocalDateTime.parse(cuidadoresTable.getModel().getValueAt(row, ++column).toString());

        CuidadorDialog d = new CuidadorDialog(this, true, id, experto, basico, fecha, especieCuidada, nombre);
        d.setVisible(true);
    }//GEN-LAST:event_itinerarioCuidadorEditarBotonActionPerformed

    private void cuidadorActualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuidadorActualizarBotonActionPerformed
        try {
            List<Cuidador> cuidadores = Control.listCuidador();
            CuidadorTable model = new CuidadorTable(cuidadores);
            cuidadoresTable.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_cuidadorActualizarBotonActionPerformed

    private void habitatActualizarTabla() {
        try {
            List<Habitat> habitats = Control.searchHabitat("");
            HabitatTable table = new HabitatTable(habitats);
            habitatTable.setModel(table);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EspecieHabitatComboBox;
    private javax.swing.JButton cuidadorActualizarBoton;
    private javax.swing.JScrollPane cuidadoresScrollPane;
    private javax.swing.JTable cuidadoresTable;
    private com.github.lgooddatepicker.components.DatePicker empleadoFechaIniciodatePicker;
    private javax.swing.JTextField empleadoNombreTextField;
    private javax.swing.JButton empleadoRegistrarBoton;
    private javax.swing.JTable empleadoTable;
    private javax.swing.JTextField empleadoTelefonoTextField;
    private javax.swing.JButton especieActualizarBoton;
    private javax.swing.JTextArea especieDescripcionTextArea;
    private javax.swing.JTextField especieNombreCientificoTextField;
    private javax.swing.JTextField especieNombreTextField;
    private javax.swing.JButton especieRegistrarBoton;
    private javax.swing.JTable especiesTable;
    private javax.swing.JButton habitatBuscarBoton;
    private javax.swing.JComboBox<String> habitatClimaCombobox;
    private javax.swing.JComboBox<String> habitatContinenteCombobox;
    private javax.swing.JButton habitatEliminarBoton;
    private javax.swing.JTextField habitatIdTextField;
    private javax.swing.JButton habitatLimpiarBoton;
    private javax.swing.JTextField habitatNombreTextField;
    private javax.swing.JButton habitatRegistrarBoton;
    private javax.swing.JScrollPane habitatScrollPane;
    private javax.swing.JTable habitatTable;
    private javax.swing.JComboBox<String> habitatVegetacionCombobox;
    private javax.swing.JButton habtitatEditarBoton;
    private javax.swing.JButton itinerarioCuidadorEditarBoton;
    private javax.swing.JButton itinerarioRegistrarCuidadorBoton;
    private javax.swing.JButton itinerarioRegistrarRecorridoBoton;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JButton quejaActualizarBoton;
    private javax.swing.JTextArea quejaDescripcionTextFileld;
    private javax.swing.JTextField quejaEmailTextFile;
    private javax.swing.JTextField quejaTelefonoTextField;
    private javax.swing.JButton quejasEliminarBoton;
    private javax.swing.JButton quejasRegistrarBoton;
    private javax.swing.JTable quejasTables;
    private javax.swing.JTable recorridosTable;
    private javax.swing.JButton zonaBuscarBoton;
    private javax.swing.JTextField zonaBuscarTextField;
    private javax.swing.JComboBox<String> zonaEspeciesComboBox;
    private javax.swing.JTextField zonaExtencionTextField;
    private javax.swing.JTextField zonaNombreTextField;
    private javax.swing.JButton zonaRegistrarBoton;
    private javax.swing.JTable zonaTable;
    // End of variables declaration//GEN-END:variables
}
